apiVersion: batch/v1
kind: CronJob
metadata:
  name: apic-swagger-cronjob
  namespace: your-namespace
spec:
  schedule: "0 0 * * *" # Runs every 24 hours
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: apic-swagger-container
            image: ab-docker-snapshots.artifactory-.net/apic-swagger-container:latest
            env:
            - name: APIC_ENVIRONMENTS
              value: "dev,sit1,sit2,prod"
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: apic-credentials
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apic-credentials
                  key: password
          restartPolicy: OnFailure
